module ApplicationHelper
  
  def format(object, option)
    if [ActiveSupport::TimeWithZone, Date, DateTime].include? object.class
      case option
      when 1
        "#{object.month}/#{object.day}/#{object.year}"
      when 2
        "#{object.month}-#{object.day}-#{object.year}"
      when 3
        "#{object.strftime("%b")} #{object.day}, #{object.year}"
      when 4
        "#{object.strftime("%B")} #{object.day}, #{object.year}"
      when 5
        "#{object.strftime("%B")} #{object.day.ordinalize}, #{object.year}"
      when 6
        "#{object.strftime("%B")} #{object.day.ordinalize}"
      when 7
        "#{object.strftime("%-H:%M")}"
      when 8
        "#{object.strftime("%l:%M")}"
      when 9
        "#{object.strftime("%l:%M %p")}"
      when 10
        "#{object.strftime("%B")}"
      when 11
        "#{object.day}"
      when 12
        "#{object.year}"
      when 13
        "There aren't this many options, use a smaller number."
      end
    end
  end
  
  def am_or_pm(object)
    
  end

  def creator_name(user)
    user == current_user ? "Me" : user.full_name
  end

  def background_url(obj)
    urls = {"School" => 'http://svite-league-apps-content.s3.amazonaws.com/bgimages/sports-wave.jpg',
     'User' => image_path('http://svite-league-apps-content.s3.amazonaws.com/bgimages/sports-wave.jpg'),
     'Team' => 'http://svite-league-apps-content.s3.amazonaws.com/bgimages/sports-wave.jpg',
     'Facility' => 'http://svite-league-apps-content.s3.amazonaws.com/bgimages/sports-wave.jpg',
     'Club' => 'http://svite-league-apps-content.s3.amazonaws.com/bgimages/sports-wave.jpg',}
    (obj.main_photo.try(:persisted?) && obj.main_photo.image.url.present?) ? obj.main_photo.image.url : urls[obj.class.to_s]
  end
  
  def state_abbreviation(city)
    case city
    when "New York City"
      "NY"
    when "Los Angeles"
      "CA"
    when "Chicago"
      "IL"
    when "Houston"
      "TX"
    when "Philadelphia"
       "PA"
    when "Phoenix"
      "AZ"
    when "San Antonio"
      "TX"
    when "San Diego"
      "CA"
    when "Dallas"
      "TX"
    when "San Jose"
      "CA"
    when "Austin"
      "TX"
    when "Jacksonville"
      "FL"
    when "Indianapolis"
      "IN"
    when "San Francisco"
      "CA"
    when "Columbus"
      "OH"
    when "Fort Worth"
      "TX"
    when "Charlotte"
      "NC"
    when "Detroit"
      "MI"
    when "El Paso"
      "TX"
    when "Memphis"
      "TN"
    when "Boston"
      "MA"
    when "Seattle"
      "WA"
    when "Denver"
      "CO"
    when "Washington"
      "DC"
    when "Nashville-Davidson"
      "TN"
    when "Baltimore"
      "MD"
    when "Louisville-Jefferson"
      "KY"
    when "Portland"
      "OR"
    when "Oklahoma City"
      "OK"
    when "Milwaukee"
      "WI"
    when "Las Vegas"
      "NV"
    when "Albuquerque"
      "NM"
    when "Tucson"
      "AZ"
    when "Fresno"
      "CA"
    when "Sacramento"
      "CA"
    when "Long Beach"
      "CA"
    when "Kansas-MO"
      "MO"
    when "Mesa"
      "AZ"
    when "Virginia Beach"
      "VA"
    when "Atlanta"
      "GA"
    when "Colorado Springs"
      "CO"
    when "Raleigh"
      "NC"
    when "Omaha"
      "NE"
    when "Miami"
      "FL"
    when "Oakland"
      "CA"
    when "Tulsa"
      "OK"
    when "Minneapolis"
      "MN"
    when "Cleveland"
      "OH"
    when "Wichita"
      "KS"
    when "Arlington"
      "TX"
    when "New Orleans"
      "LA"
    when "Bakersfield"
      "CA"
    when "Tampa"
      "FL"
    when "Honolulu"
      "HI"
    when "Anaheim"
      "CA"
    when "Aurora-CO"
      "CO"
    when "Santa Ana"
      "CA"
    when "St. Louis"
      "MO"
    when "Riverside"
      "CA"
    when "Corpus Christi"
      "TX"
    when "Pittsburgh"
      "PA"
    when "Lexington-Fayette"
      "KY"
    when "Anchorage"
      "AL"
    when "Stockton"
      "CA"
    when "Cincinnati"
      "OH"
    when "St. Paul"
      "MN"
    when "Toledo"
      "OH"
    when "Newark"
      "NJ"
    when "Greensboro"
      "NC"
    when "Plano"
      "TX"
    when "Henderson"
      "NV"
    when "Lincoln"
      "NE"
    when "Buffalo"
      "NY"
    when "Fort Wayne"
      "IN"
    when "Jersey City"
      "NJ"
    when "Chula Vista"
      "CA"
    when "Orlando"
      "FL"
    when "St. Petersburg"
      "FL"
    when "Norfolk"
      "VA"
    when "Chandler"
      "AZ"
    when "Laredo"
      "TX"
    when "Madison"
      "WI"
    when "Durham"
      "NC"
    when "Lubbock"
      "TX"
    when "Winston-Salem"
      "NC"
    when "Garland"
      "TX"
    when "Glendale"
      "AZ"
    when "Hialeah"
      "FL"
    when "Reno"
      "NV"
    when "Baton Rouge"
      "LA"
    when "Irvine"
      "CA"
    when "Chesapeake"
      "VA"
    when "Irving"
      "TX"
    when "Scottsdale"
      "AZ"
    when "North Las Vegas"
      "NV"
    when "Fremont"
      "CA"
    when "Gilbert"
      "AZ"
    when "San Bernardino"
      "CA"
    when "Boise"
      "ID"
    when "Birmingham"
      "AL"
    when "Rochester"
      "NY"
    when "Richmond"
      "VA"
    when "Spokane"
        "WA"
    when "Des Moines"
      "IA"
    when "Montgomery"
      "AL"
    when "Modesto"
      "CA"
    when "Fayetteville"
       "NC"
    when "Tacoma"
      "WA"
    when "Shreveport"
      "LA"
    when "Fontana"
      "CA"
    when "Oxnard"
      "CA"
    when "Aurora-IL"
      "IL"
    when "Moreno Valley"
      "CA"
    when "Akron"
      "OH"
    when "Yonkers"
      "NY"
    when "Columbus-GA"
      "GA"
    when "Augusta-Richmond"
      "GA"
    when "Little Rock"
      "AR"
    when "Amarillo"
      "TX"
    when "Mobile"
      "AL"
    when "Huntington Beach"
      "CA"
    when "Glendale"
      "CA"
    when "Grand Rapids"
      "MI"
    when "Salt Lake City"
      "UT"
    when "Tallahassee"
      "FL"
    when "Huntsville"
      "AL"
    when "Worcester"
      "MA"
    when "Knoxville"
      "TN"
    when "Grand Prairie"
      "TX"
    when "Newport News"
      "VA"
    when "Brownsville"
      "TX"
    when "Santa Clarita"
      "CA"
    when "Overland Park"
      "KS"
    when "Providence"
      "RI"
    when "Jackson"
      "MS"
    when "Garden Grove"
      "CA"
    when "Oceanside"
      "CA"
    when "Chattanooga"
      "TN"
    when "Fort Lauderdale"
      "FL"
    when "Rancho Cucamonga"
      "CA"
    when "Santa Rosa"
      "CA"
    when "Port St. Lucie"
      "FL"
    when "Ontario"
      "CA"
    when "Tempe"
      "AZ"
    when "Vancouver"
      "WA"
    when "Springfield-MO"
      "MO"
    when "Cape Coral"
      "FL"
    when "Pembroke Pines"
      "FL"
    when "Sioux Falls"
      "SD"
    when "Peoria"
      "AZ"
    when "Lancaster"
      "CA"
    when "Elk Grove"
      "CA"
    when "Corona"
      "CA"
    when "Eugene"
      "OR"
    when "Salem"
      "OR"
    when "Palmdale"
      "CA"
    when "Salinas"
      "CA"
    when "Springfield-MA"
      "MA"
    when "Pasadena-TX"
      "TX"
    when "Rockford"
      "IL"
    when "Pomona"
      "CA"
    when "Hayward"
      "CA"
    when "Fort Collins"
      "CO"
    when "Joliet"
       "IL"
    when "Escondido"
      "CA"
    when "Kansas-KS"
      "KS"
    when "Torrance"
      "CA"
    when "Bridgeport"
      "CT"
    when "Alexandria"
      "VA"
    when "Sunnyvale"
      "CA"
    when "Cary"
      "NC"
    when "Lakewood"
      "CO"
    when "Hollywood"
      "FL"
    when "Paterson"
      "NJ"
    when "Syracuse"
      "NY"
    when "Naperville"
      "IL"
    when "McKinney"
      "TX"
    when "Mesquite"
      "TX"
    when "Clarksville"
      "TN"
    when "Savannah"
      "GA"
    when "Dayton"
      "OH"
    when "Orange"
      "CA"
    when "Fullerton"
      "CA"
    when "Pasadena"
      "CA"
    when "Hampton"
      "VA"
    when "McAllen"
      "TX"
    when "Killeen"
      "TX"
    when "Warren"
      "MI"
    when "West Valley"
      "UT"
    when "Columbia"
      "SC"
    when "New Haven"
      "CT"
    when "Sterling Heights"
      "MI"
    when "Olathe"
      "KS"
    when "Miramar"
      "FL"
    when "Thousand Oaks"
      "CA"
    when "Frisco"
      "TX"
    when "Cedar Rapids"
      "IA"
    when "Topeka"
      "KS"
    when "Visalia"
      "CA"
    when "Waco"
      "TX"
    end
  end
  
  def city_with_state(city)
    "#{city}, #{state_abbreviation(city)}"
  end
  
  def add_or_remove_facility_button(ownerable_type, ownerable_id, facility_id)
    unless ownerable_type.constantize.find(ownerable_id).connects.where(connectable_type: "Facility", connectable_id: facility_id).present?      
      render partial: 'facility_links/add', :locals => {facility_id: facility_id, ownerable_type: ownerable_type, ownerable_id: ownerable_id}
    else
      connection = ownerable_type.constantize.find(ownerable_id).connects.where(connectable_type: "Facility", connectable_id: facility_id).last
      render partial: 'facility_links/remove', :locals => {connection: connection}
    end
  end
  
  def join_object_button(current_user, object_type, object_id)
	  if current_user
			 if current_user.roles.where(roleable_type: object_type, roleable_id: object_id, status: "Active").present? 
         render partial: 'roles/member_button'
       elsif current_user.roles.where(roleable_type: object_type, roleable_id: object_id, status: "Pending").present? 
			   render partial: 'roles/pending_button'
       elsif current_user.roles.where(roleable_type: object_type, roleable_id: object_id).empty? 
			   render partial: 'roles/join_button'
			 end 
	  end
  end
  
  def to_slug(*strings)
    array = []
     strings.each do |string|
       array << string.to_s.downcase unless string.nil?
     end
    array.join(" ").downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '').gsub("- ", "").gsub("--", "-")
  end
    
  

end
