class ChangeForm < ActiveRecord::Migration
  def change
    remove_column :forms, :section_1
    remove_column :forms, :form_name
    remove_column :forms, :form_description
    remove_column :forms, :object
    remove_column :forms, :section_2
    remove_column :forms, :first_name
    remove_column :forms, :middle_name
    remove_column :forms, :last_name
    remove_column :forms, :prefix
    remove_column :forms, :suffix
    remove_column :forms, :date_of_birth
    remove_column :forms, :mobile_phone_number
    remove_column :forms, :home_phone_number
    remove_column :forms, :sex
    remove_column :forms, :address
    remove_column :forms, :ethnicity
    remove_column :forms, :lives_with
    remove_column :forms, :t_shirt_size
    remove_column :forms, :section_3
    remove_column :forms, :membership_status
    remove_column :forms, :membership_status_options
    remove_column :forms, :section_4
    remove_column :forms, :allergies
    remove_column :forms, :medical_conditions
    remove_column :forms, :medications
    remove_column :forms, :section_5
    remove_column :forms, :school_name
    remove_column :forms, :school_district
    remove_column :forms, :section_6
    remove_column :forms, :guardian_1_name
    remove_column :forms, :guardian_1_relationship
    remove_column :forms, :guardian_1_address
    remove_column :forms, :guardian_1_phone
    remove_column :forms, :guardian_1_email
    remove_column :forms, :guardian_2_name
    remove_column :forms, :guardian_2_relationship
    remove_column :forms, :guardian_2_address
    remove_column :forms, :guardian_2_phone
    remove_column :forms, :guardian_2_email
    remove_column :forms, :section_7
    remove_column :forms, :emergency_1_name
    remove_column :forms, :emergency_1_relationship
    remove_column :forms, :emergency_1_address
    remove_column :forms, :emergency_1_phone
    remove_column :forms, :emergency_1_email
    remove_column :forms, :emergency_2_name
    remove_column :forms, :emergency_2_relationship
    remove_column :forms, :emergency_2_address
    remove_column :forms, :emergency_2_phone
    remove_column :forms, :emergency_2_email
    remove_column :forms, :section_8
    remove_column :forms, :insurance_company
    remove_column :forms, :insurance_policy_number
    remove_column :forms, :insurance_group_number
    remove_column :forms, :employer_insurance
    remove_column :forms, :employer_name
    remove_column :forms, :section_9
    remove_column :forms, :special_assistance_programs
    remove_column :forms, :annual_family_income
    remove_column :forms, :number_in_household
    remove_column :forms, :section_10
    remove_column :forms, :waiver
    remove_column :forms, :accept_waiver
    remove_column :forms, :agreements
    remove_column :forms, :first_name_required
    remove_column :forms, :middle_name_required
    remove_column :forms, :last_name_required
    remove_column :forms, :prefix_required
    remove_column :forms, :suffix_required
    remove_column :forms, :date_of_birth_required
    remove_column :forms, :mobile_phone_number_required
    remove_column :forms, :home_phone_number_required
    remove_column :forms, :sex_required
    remove_column :forms, :address_required
    remove_column :forms, :ethnicity_required
    remove_column :forms, :lives_with_required
    remove_column :forms, :t_shirt_size_required
    remove_column :forms, :membership_status_required
    remove_column :forms, :allergies_required
    remove_column :forms, :medical_conditions_required
    remove_column :forms, :medications_required
    remove_column :forms, :school_name_required
    remove_column :forms, :school_district_required
    remove_column :forms, :guardian_1_name_required
    remove_column :forms, :guardian_1_relationship_required
    remove_column :forms, :guardian_1_address_required
    remove_column :forms, :guardian_1_phone_required
    remove_column :forms, :guardian_1_email_required
    remove_column :forms, :guardian_2_name_required
    remove_column :forms, :guardian_2_relationship_required
    remove_column :forms, :guardian_2_address_required
    remove_column :forms, :guardian_2_phone_required
    remove_column :forms, :guardian_2_email_required
    remove_column :forms, :emergency_1_name_required
    remove_column :forms, :emergency_1_relationship_required
    remove_column :forms, :emergency_1_address_required
    remove_column :forms, :emergency_1_phone_required
    remove_column :forms, :emergency_1_email_required
    remove_column :forms, :emergency_2_name_required
    remove_column :forms, :emergency_2_relationship_required
    remove_column :forms, :emergency_2_address_required
    remove_column :forms, :emergency_2_phone_required
    remove_column :forms, :emergency_2_email_required
    remove_column :forms, :insurance_company_required
    remove_column :forms, :insurance_policy_number_required
    remove_column :forms, :insurance_group_number_required
    remove_column :forms, :employer_insurance_required
    remove_column :forms, :employer_name_required
    remove_column :forms, :special_assistance_programs_required
    remove_column :forms, :annual_family_income_required
    remove_column :forms, :number_in_household_required
    remove_column :forms, :first_name_display
    remove_column :forms, :middle_name_display
    remove_column :forms, :last_name_display
    remove_column :forms, :prefix_display
    remove_column :forms, :suffix_display
    remove_column :forms, :date_of_birth_display
    remove_column :forms, :mobile_phone_number_display
    remove_column :forms, :home_phone_number_display
    remove_column :forms, :sex_display
    remove_column :forms, :address_display
    remove_column :forms, :ethnicity_display
    remove_column :forms, :lives_with_display
    remove_column :forms, :t_shirt_size_display
    remove_column :forms, :membership_status_display
    remove_column :forms, :allergies_display
    remove_column :forms, :medical_conditions_display
    remove_column :forms, :medications_display
    remove_column :forms, :school_name_display
    remove_column :forms, :school_district_display
    remove_column :forms, :guardian_1_name_display
    remove_column :forms, :guardian_1_relationship_display
    remove_column :forms, :guardian_1_address_display
    remove_column :forms, :guardian_1_phone_display
    remove_column :forms, :guardian_1_email_display
    remove_column :forms, :guardian_2_name_display
    remove_column :forms, :guardian_2_relationship_display
    remove_column :forms, :guardian_2_address_display
    remove_column :forms, :guardian_2_phone_display
    remove_column :forms, :guardian_2_email_display
    remove_column :forms, :emergency_1_name_display
    remove_column :forms, :emergency_1_relationship_display
    remove_column :forms, :emergency_1_address_display
    remove_column :forms, :emergency_1_phone_display
    remove_column :forms, :emergency_1_email_display
    remove_column :forms, :emergency_2_name_display
    remove_column :forms, :emergency_2_relationship_display
    remove_column :forms, :emergency_2_address_display
    remove_column :forms, :emergency_2_phone_display
    remove_column :forms, :emergency_2_email_display
    remove_column :forms, :insurance_company_display
    remove_column :forms, :insurance_policy_number_display
    remove_column :forms, :insurance_group_number_display
    remove_column :forms, :employer_insurance_display
    remove_column :forms, :employer_name_display
    remove_column :forms, :special_assistance_programs_display
    remove_column :forms, :annual_family_income_display
    remove_column :forms, :number_in_household_display
  end
end
